### ISSUE TITLE
cuDNN failed to initialize

### ISSUE THREAD

**Issue by lhanzl** [athena-team/athena#104]
806c16f609ef8cec729b118952df2547a01875b9

Hello, genius developer
I am a shenlan student. I installed it according to the instructions. No errors were reported in the middle, and I used the following code to verify that the translation model training is correct.
However, when I train the asr model in the examples/asr/aishell_sub/ directory and run to Fine-tuning, an error is reported.

Traceback (most recent call last):
  File "athena/main.py", line 172, in <module>
    train(json_file, BaseSolver, 1, 0)
  File "athena/main.py", line 117, in train
    p, model, optimizer, checkpointer = build_model_from_jsonfile(jsonfile)
  File "athena/main.py", line 105, in build_model_from_jsonfile
    solver.evaluate_step(model.prepare_samples(iter(dataset).next()))
  File "/home/hanzl/work/learn/athena/athena/solver.py", line 95, in evaluate_step
    logits = self.model(samples, training=False)
...
...
  File "/home/hanzl/work/learn/athena/venv_athena/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]

It prompts me to go to the error message above, I found the following information：

2020-04-06 14:48:17.829495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10283 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080 Ti, pci bus id: 0000:b1:00.0, compute capability: 7.5)
INFO:absl:trying to restore from : examples/asr/aishell/ckpts/mtl_transformer_ctc/
2020-04-06 14:48:21.230124: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-06 14:48:22.942435: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.5.0 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.

Can anyone tell me why this is and how should I solve it? I look forward to your reply, thank you very much!

**Comment by Some-random** [comment]
According to your error message, you probably need to upgrade your cudnn version to 7.6.0. Did you use the same cudnn for installation and running?

**Comment by lhanzl** [comment]
Same cudnn for installation and running.

**Comment by Some-random** [comment]
Then I think you should upgrade cudnn to 7.6.0 and see if this problem still persists.

**Comment by lhanzl** [comment]
Thank you very much, I installed the cudnn7.6 version by referring to this link, 
http://www.tensorfly.cn/tfdoc/get_started/os_setup.html,and this problem is solved.
However, I carefully checked my system. At first, cudnn was not installed, but my installation did not report an error. 
I do not know, how did the code (" tensorflow/stream_executor/cuda/cuda_dnn.cc")find cudnn version 7.5 at runtime. I am using TensorFlow for the first time, can you tell me the specific reason? Thank you~

**Comment by Some-random** [comment]
Sorry, I'm not an expert on CUDNN and CUDA installation. And IMHO this question is better asked on StackOverflow.

**Comment by lhanzl** [comment]
OK, Thanks.
